Python. Let's work through an example to see why & how to use Numpy for working with numerical data.

Suppose we want to use climate data like the temperature, rainfall, and humidity to determine if a region is well suited for growing apples. A simple approach for doing this would be to formulate the relationship between the annual yield of apples (tons per hectare) and the climatic conditions like the average temperature (in degrees Fahrenheit), rainfall (in millimeters) & average relative humidity (in percentage) as a linear equation.

yield_of_apples = w1 * temperature + w2 * rainfall + w3 * humidity

We're expressing the yield of apples as a weighted sum of the temperature, rainfall, and humidity. This equation is an approximation since the actual relationship may not necessarily be linear, and there may be other factors involved. But a simple linear model like this often works well in practice

In [1]:
w1 , w2 , w3 = 0.3 , 0.2 , 0.5

In [2]:
Kanto_temp = 73
Kanto_rainfall = 67
Kanto_humidity = 43

In [3]:
yield_of_apples = w1 * Kanto_temp + w2 * Kanto_rainfall + w3 * Kanto_humidity

In [4]:
yield_of_apples

56.8

Through lists

!["data_of_regions"](data.png)

In [5]:
kanto = [ 73 , 67 , 43 ]
johto = [ 91 , 88 , 64 ]
hoenn = [ 87 , 134 , 58 ]
sinnoh = [ 102 , 43 , 37 ]
unova = [ 69 , 96 , 70 ]


In [6]:
weights = [ w1 , w2 ,w3 ]

In [7]:
result = 0
for x,w in zip(kanto,weights):
    result += x * w
print(result)

56.8


In [8]:
def crop_yields(region,weights):
    result = 0
    for x,w in zip(region,weights):
        result += x * w
    return result

In [9]:
crop_yields(kanto,weights)

56.8

In [10]:
crop_yields(unova,weights)

74.9

#### Numpy

In [11]:
import numpy as np

In [12]:
kanto = np.array([73 , 67 , 43 ])

In [13]:
weights = np.array([w1 ,w2 ,w3])

In [14]:
np.dot(kanto,weights)

56.8

In [15]:
weights.shape

(3,)

In [16]:
kanto.shape

(3,)

In [17]:
weights.dtype

dtype('float64')

In [18]:
kanto.dtype

dtype('int64')

In [19]:
type(kanto)

numpy.ndarray

In [20]:
type(weights)

numpy.ndarray

### Multidimensional Arrays

In [21]:
climate_data = np.array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [22]:
climate_data.shape

(5, 3)

In [23]:
weights.shape

(3,)

### Data is in Matrix so matmul

In [24]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [25]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

### 3-D array

In [26]:
array = np.array([
    [[72,64,65],
     [23,231,213],
     [123,3,455]],
    
    [[211,213,321],
     [321,321,321],
     [321231,321,21]]
         
         
         ])

In [27]:
array.shape

(2, 3, 3)

### Working with CSV Data
to read a csv file in <b> Numpy, genfromtxt </b> is used

In [28]:
import urllib.request
urllib.request.urlretrieve( 'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')


('climate.txt', <http.client.HTTPMessage at 0x7ff2fa7dae20>)

In [29]:
climate_data = np.genfromtxt("climate.txt",delimiter = "," , skip_header = True)

In [30]:
climate_data.shape

(10000, 3)

In [31]:
weights.shape

(3,)

In [32]:
yields = np.matmul(climate_data,weights)

In [33]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

Let's add the yields to climate_data as a fourth column using the np.concatenate function.



In [34]:
climate_results = np.concatenate((climate_data,yields.reshape(10000,1)), axis = 1)

In [35]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [36]:
np.savetxt("climate_results.txt",
          climate_results,
          fmt = '%.2f',
          delimiter = ",",
          header = "temperature,rainfall,humditiy,yeilds",
          comments = "")


## Arithematic Operations and Broadcasting

In [38]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3]])
arr2 = np.array([[11,12,13,14],[15,16,17,18],[19,20,21,22]])

## Element Wise Operations

In [40]:
arr1 * arr2 #multiplication element wise

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  20,  42,  66]])

In [41]:
arr2 - arr1 #subtraction element wise

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 19, 19, 19]])

In [43]:
arr2 / 2 #division element wise by scalar

array([[ 5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ],
       [ 9.5, 10. , 10.5, 11. ]])

### If dimensions of two arrays does not match , numpy do broadcasting

In [45]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr2 = np.array([1,2,3,4])

In [46]:
arr1.shape

(3, 4)

In [47]:
arr2.shape

(4,)

### the shape of column of first array should match the shape of second array , the numpy don't coppy 2nd arrays value but replication it according to the rows of first array

In [48]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

#### Element Wise Operations on Arrays

In [49]:
arr1 = np.array([[1,2,3,4],
         [5,6,7,8]])

arr2 = np.array([[2,1,3,4],
                [5,7,6,8]])


In [50]:
arr1 == arr2

array([[False, False,  True,  True],
       [ True, False, False,  True]])

In [51]:
arr1 >=arr2

array([[False,  True,  True,  True],
       [ True, False,  True,  True]])

In [52]:
arr1 != arr2

array([[ True,  True, False, False],
       [False,  True,  True, False]])

In [53]:
np.sum(arr1 == arr2)

4

### Other Numpy Functions

In [54]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [55]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.full([4,3],42)

array([[42, 42, 42],
       [42, 42, 42],
       [42, 42, 42],
       [42, 42, 42]])

In [57]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
np.arange(10,90,3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [63]:
#equally space numbers
np.linspace(3,27,9)  #9 are the elements

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])